int    test1(void) { return '\\'; }
int test2(void) { return L'\\'; }
int    test3(void) { return '\''; }
int test4(void) { return L'\''; }
int    test5(void) { return '\a'; }
int test6(void) { return L'\a'; }
int    test7(void) { return '\b'; }
int test8(void) { return L'\b'; }
int    test11(void) { return '\f'; }
int test12(void) { return L'\f'; }
int    test13(void) { return '\n'; }
int test14(void) { return L'\n'; }
int    test15(void) { return '\r'; }
int test16(void) { return L'\r'; }
int    test17(void) { return '\t'; }
int test18(void) { return L'\t'; }
int    test19(void) { return '\v'; }
int test20(void) { return L'\v'; }
int    test21(void) { return 'c'; }
int test22(void) { return L'c'; }
int    test23(void) { return '\x3'; }
int test24(void) { return L'\x3'; }
int test25(void) { return L'\x333'; }
